apiVersion: v1
kind: Secret
metadata:
  name: microb-postgres-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/{{ .Values.postgres.credentials.database }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.credentials.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.credentials.password }}


#### {{ range $key, $value := .Values.stringData }}
####  {{ $key }}: {{ $value }}
####  {{ end }} not bad option if we woudn't templatize our stringdata already