apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-2
spec:
  replicas: {{ .Values.backendTwo.replicas }}
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
        - name: server2
          image: {{ .Values.backendTwo.image }}:{{ .Values.backendTwo.tag }}
          ports:
            - containerPort: {{ .Values.backendTwo.service.port }}
